### ISSUE TITLE
Unexpected error fetching sensor data

### ISSUE THREAD

**Issue by bfroeba** [vermi0ffh/ha-windhager#16]
Hello,
I get the following error log when adding my heater via ip/password:
2024-12-25 04:19:27.593 DEBUG (MainThread) [custom_components.windhager] Finished fetching sensor data in 3.516 seconds (success: False)
2024-12-25 04:19:39.032 ERROR (MainThread) [custom_components.windhager] Unexpected error fetching sensor data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 280, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/windhager/__init__.py", line 36, in async_update_data
    return await httpClient.fetch_all()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/windhager/client.py", line 502, in fetch_all
    ret["oids"][oid] = json["value"]
                       ~~~~^^^^^^^^^
KeyError: 'value'


What could I do?

**Comment by bfroeba** [comment]
Sorry, my issue is the same as issue11. But it is very difficult for a Home Assistant Newby to work with a HACS software with a special branch "issue11". Is it possible to merge the already made bugfixes in the main branch???

**Comment by jannemannX** [comment]
> Sorry, my issue is the same as issue11. But it is very difficult for a Home Assistant Newby to work with a HACS software with a special branch "issue11". Is it possible to merge the already made bugfixes in the main branch???

Fork the repo -> create a release in your forked repo -> add it the regular way 

Or just use the latest release from @zaphod0x2A windhager repo (v0.0.4 is just the bugfix branch merged and released)
