### ISSUE TITLE
Problem bei Einrichtung

### ISSUE THREAD

**Issue by oberberger9** [vermi0ffh/ha-windhager#9]
Hi,

bekomme die Fehlermeldung Einrichtung fehlgeschlagen. 

Log gibt folgendes aus:

:34.279 ERROR (MainThread) [custom_components.windhager] Unexpected error fetching sensor data: 'value'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 313, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 269, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/windhager/__init__.py", line 36, in async_update_data
    return await httpClient.fetch_all()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/windhager/client.py", line 502, in fetch_all
    ret["oids"][oid] = json["value"]
                       ~~~~^^^^^^^^^

Es wurden folgende Geräte gefunden:

[
    {
        "device": {
            "DeviceClass": "20.12",
            "id": 6,
            "name": "BioWIN-II",
            "protocol": "WinFA"
        },
        "name": "BioWIN-II",
        "neuronId": "07001851d401",
        "nodeId": 60,
        "programId": "900100140c0a0514",
        "subnet": 1
    },
    {
        "name": "UML HK1",
        "neuronId": "070016bfd401",
        "nodeId": 15,
        "programId": "9001001c010a0533",
        "subnet": 1
    },
    {
        "name": "B-PLM",
        "neuronId": "07001d8d2401",
        "nodeId": 16,
        "programId": "9001001c020a0535",
        "subnet": 1
    }
]

**Comment by jovicde** [comment]
@oberberger9 Hast du das Problem lösen können? Ich habe vermutlich ein ganz ähnliches: #11

**Comment by hartmannf** [comment]
Hallo 

I really like your approach to get access of process Data on windhager heating. 
Up to now I haven`t installed Homeassitant because I am using Openhab, with a beckhoff binding. How ever before I start to get into HA (spending time without chance of success) would like to know if there is a chance to get connected over HA the Windhager Biowin 2 Touch? 
I already tried over the Webinterface to straith on connect to webinderface without any success. 
the password on an Biowin 2 Pelletoven installed 2023 with sw version v3.31 hardware version D10 Type: BW102E I have tried several User and password. 
User :service PW: 123 also my same user and password that is used for iphone app to connect https://connect.windhager.com/
I read that reseting the windhager and not allowing to internet acces might be a possibility to access, but I haven`t tried it yet. 
I also tried to convince my "windhager representativ" but he is technically blocking for what ever reason to open contect directly to windhager technician. How ever I try to get info over that way and perhaps somebdy could guide me and give me hope that it might be someday possible to get also my biowin Online and connected to my or any homeautomation. 
Thanks for suggestions of any kind. 
KR
Francis
